services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      
  api:
    build:
      context: . 
      dockerfile: apps/backend/Dockerfile
    image: encodr-backend 
    command: node ./dist/app.js
    ports:
      - "3000:3000"
    env_file:
      - apps/backend/.env 
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  transcode-worker:
    image: encodr-backend
    command: node ./dist/transcode-worker.js
    env_file:
      - apps/backend/.env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - api 
    deploy:
      replicas: 1

  upload-worker:
    image: encodr-backend
    command: node ./dist/upload-worker.js
    env_file:
      - apps/backend/.env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - api 

  sqs-consumer:
    image: encodr-backend
    command: node ./dist/sqs-consumer.js
    env_file:
      - apps/backend/.env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - api